upstream auth_service {
    server auth-service:8081;
}

upstream content_service {
    server content-service:8082;
}

upstream course_service {
    server course-service:8083;
}

upstream document_service {
    server document-service:8084;
}

upstream statistic_service {
    server statistic-service:8085;
}

upstream recommendation_service {
    server recommendation-service:8091;
}

server {
    listen 80;
    server_name _;

    location /healthz {
        add_header Content-Type application/json;
        return 200 '{"service":"gateway","status":"ok"}';
    }

    location /auth/ {
        rewrite ^/auth/(.*)$ /$1 break;
        proxy_pass http://auth_service;
    }

    location /content/ {
        rewrite ^/content/(.*)$ /$1 break;
        proxy_pass http://content_service;
    }

    location /courses {
        proxy_pass http://course_service;
    }

    location /assignments {
        proxy_pass http://course_service;
    }

    location /submissions {
        proxy_pass http://course_service;
    }

    location /documents/ {
        proxy_pass http://document_service;
    }

    location /statistics/ {
        rewrite ^/statistics/(.*)$ /$1 break;
        proxy_pass http://statistic_service;
    }

    location /recommendations/ {
        proxy_pass http://recommendation_service;
    }
}
